name: 'lightdash_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lightdash_analytics:
    # Models in staging folder
    staging:
      +materialized: view
    
    # Models in marts folder  
    marts:
      +materialized: table
