version: 2

models:
  - name: stg_google_ads
    description: "Google Ads staging data"
    columns:
      - name: campaign_name
        meta:
          dimension:
            type: string
      - name: date
        meta:
          dimension:
            type: date
      - name: clicks
        meta:
          metrics:
            total_clicks:
              type: sum
