version: 2

models:
  - name: stg_google_ads
    description: "Staging model for Google Ads with calculated metrics"
    columns:
      - name: id
        description: "Unique identifier"
        meta:
          dimension:
            type: number
            
      - name: campaign_name
        description: "Campaign name"
        meta:
          dimension:
            type: string
            
      - name: ad_group
        description: "Ad group name"
        meta:
          dimension:
            type: string
            
      - name: date
        description: "Date of the ad data"
        meta:
          dimension:
            type: date
            
      - name: clicks
        description: "Total clicks"
        meta:
          metrics:
            total_clicks:
              type: sum
              
      - name: impressions
        description: "Total impressions"
        meta:
          metrics:
            total_impressions:
              type: sum
              
      - name: cost
        description: "Total cost"
        meta:
          metrics:
            total_cost:
              type: sum
              round: 2
              
      - name: conversions
        description: "Total conversions"
        meta:
          metrics:
            total_conversions:
              type: sum
              
      - name: cost_per_click
        description: "Cost per click"
        meta:
          metrics:
            avg_cpc:
              type: average
              round: 2
              
      - name: click_through_rate
        description: "Click through rate"
        meta:
          metrics:
            avg_ctr:
              type: average
              round: 2

  - name: stg_shopify_orders
    description: "Staging model for Shopify orders"
    columns:
      - name: id
        meta:
          dimension:
            type: number
            
      - name: order_id
        meta:
          dimension:
            type: string
            
      - name: customer_email
        meta:
          dimension:
            type: string
            
      - name: order_date
        meta:
          dimension:
            type: timestamp
            
      - name: order_date_only
        meta:
          dimension:
            type: date
            
      - name: total_price
        meta:
          metrics:
            total_revenue:
              type: sum
              round: 2
            avg_order_value:
              type: average
              round: 2

  - name: stg_meta_ads
    description: "Staging model for Meta Ads with calculated metrics"
    columns:
      - name: id
        meta:
          dimension:
            type: number
            
      - name: campaign_name
        meta:
          dimension:
            type: string
            
      - name: ad_set_name
        meta:
          dimension:
            type: string
            
      - name: date
        meta:
          dimension:
            type: date
            
      - name: clicks
        meta:
          metrics:
            total_clicks:
              type: sum
              
      - name: impressions
        meta:
          metrics:
            total_impressions:
              type: sum
              
      - name: spend
        meta:
          metrics:
            total_spend:
              type: sum
              round: 2
              
      - name: conversions
        meta:
          metrics:
            total_conversions:
              type: sum
              
      - name: cost_per_click
        meta:
          metrics:
            avg_cpc:
              type: average
              round: 2
              
      - name: click_through_rate
        meta:
          metrics:
            avg_ctr:
              type: average
              round: 2