version: 2

models:
  - name: daily_marketing_performance
    description: "Daily aggregated marketing performance across all platforms"
    columns:
      - name: date
        description: "Date of performance"
      - name: platform
        description: "Ad platform (Google Ads or Meta Ads)"
      - name: total_clicks
        description: "Total clicks for the day"
      - name: total_impressions
        description: "Total impressions"
      - name: total_spend
        description: "Total ad spend"
      - name: total_conversions
        description: "Total conversions"
      - name: avg_ctr
        description: "Average click-through rate"
      - name: avg_cpc
        description: "Average cost per click"
      - name: cost_per_conversion
        description: "Cost per conversion"
      - name: conversion_rate
        description: "Conversion rate percentage"

  - name: revenue_summary
    description: "Daily revenue and order metrics"
    columns:
      - name: date
        description: "Order date"
      - name: total_orders
        description: "Number of orders"
      - name: total_revenue
        description: "Total revenue"
      - name: avg_order_value
        description: "Average order value"
      - name: unique_customers
        description: "Number of unique customers"
      - name: revenue_per_customer
        description: "Revenue per customer"
